project_id = "baby-tma"

[functions.analytics-events]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.analytics-dashboard]
verify_jwt = false

[functions.telegram-notifications]
verify_jwt = false
